---
- hosts: all
  become: true
  gather_facts: no
  tasks:

  - name: Update apt
    remote_user: ubuntu
    apt:
      update_cache: yes

  - name: Instalar os pacotes recomendados pro docker e para o ansible
    apt: 
      pkg:
        - apt-transport-https
        - software-properties-common
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest 

  - name: Adiciona a chave do repositorio do docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add o repositorio
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Atualiza o apt e instala o docker e o docker-compose
    apt: 
      update_cache: yes 
      pkg:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
        - docker-compose
      state: latest

  - name: Add user ubuntu no grupo docker
    remote_user: ubuntu
    user:
      name: "ubuntu"
      group: "docker"
      append: yes

  - name: Baixar repo do docker-compose (Jenkins e Sonarqube)
    git:
      repo: https://github.com/thiagoalmeidadon/devsecops-docker-compose.git
      dest: /home/ubuntu/devsecops-docker-compose
  
  - name: Executando docker-compose
    docker_compose:
      project_src: /home/ubuntu/devsecops-docker-compose
    register: output